# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application CI tests

on:
  pull_request:
  push:
    branches:
      - master
    paths:
      - tests/**
      - '**.py'
      - .github/**

permissions:
  contents: read

jobs:
  ubuntu-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest]
        python-version: ["3.8", "3.10"]
        # No need to test any python version on multiple Ubuntu versions, the Ubuntu version is
        # only to provide best matching environment for the Python.
        exclude:
          - os: ubuntu-latest
            python-version: "3.8"
          - os: ubuntu-20.04
            python-version: "3.10"
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyserial # we do not have a package, so install manually
        pip install flake8 pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 ./*.py --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 ./*.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest tests -o log_cli=true
